### ISSUE TITLE
Compile to CIL

### ISSUE THREAD

**Issue by mcmonkey4eva** [FreneticLLC/FreneticScript#9]
We should compile scripts partially down to CIL ( https://en.wikipedia.org/wiki/Common_Intermediate_Language ) for the sake of efficiency / run speed.

This would primarily affect a few key points:
- Variable control can be done more rapidly.
- If / goto / while / foreach / etc. can be speed up.
- The general queue run speed should be boosted noticeably, in theory.

There are drawbacks too of course:
- Error management will be more of a challenge.
- WAIT will be a very odd case indeed.

**Comment by mcmonkey4eva** [comment]
In progress!

**Comment by Morphan1** [comment]
wat

**Comment by mcmonkey4eva** [comment]
It's not perfect but this is being done. A ton of stuff compilers cleverly!
